name: Zizmor

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run Zizmor
        uses: woodruffw/zizmor-action@4a8b2bc9b9f83cfe0804c8f9f1e76ee85a1bee16 # v1.9.3
        with:
          config: null
